apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: cr-bdgateway-mount
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - image: us-central1-docker.pkg.dev/PROJECT/docker-bdgateway/bdgateway-mount:latest
